### ISSUE TITLE
singlefetch `Error: Unable to decode turbo-stream response from URL: <URL>`

### ISSUE THREAD

**Issue by jorisre** [vercel/remix#126] opened 2024-08-02 05:49 UTC
### Reproduction

**With Singlefetch enabled**

1. Visit the deployed version at this link: https://vercel-remix-fetch-bug.vercel.app/login
2. Click _Login & Redirect_ to submit the action
3. The app then crashes.

Repo: https://github.com/jorisre/vercel-remix-fetch-bug
Preview: https://vercel-remix-fetch-bug.vercel.app/login

**Note : everything is working well in local env.**

### Expected Behavior

Should not throw an error.

### Actual Behavior

When I attempt to submit the login, I encounter the following error :

> Error: Unable to decode turbo-stream response from URL: https://vercel-remix-fetch-bug.vercel.app/login.data
    at Xa (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:148:1818)
    at async https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:148:267
    at async f (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:185:1603)
    at async https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:148:201
    at async Fy (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:50:5399)
    at async https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:148:155
    at async Promise.all (index 1)
    at async zy (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:50:4050)
    at async Lr (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:49:29287)
    at async op (https://vercel-remix-fetch-bug.vercel.app/assets/components-BAqPFZ9s.js:49:21541)

The application functions when I deactivate singlefetch.

Here are some related investigations:
On Remix's end: https://github.com/remix-run/remix/issues/9809
On Vercel's end: https://github.com/vercel/remix/issues/124

**Comment by TooTallNate** [comment] 2024-08-02 06:04
This is actually a duplicate of #124, and the rollout of that fix is still pending (should be live in the next day or so).

Here's a working deployment after I [set the env var as described in my comment](https://github.com/vercel/remix/issues/124#issuecomment-2253590195) on the other issue: https://vercel-remix-fetch-cyfln1rnb-uncurated-tests.vercel.app/login

**Closed by TooTallNate** 2024-08-02 06:04 UTC

**Comment by jorisre** [comment] 2024-08-16 10:25
I applied the solution you provided to my company project, but unfortunately, the issue persists.

> This is actually a duplicate of #124, and the rollout of that fix is still pending (should be live in the next day or so).
> 
> Here's a working deployment after I [set the env var as described in my comment](https://github.com/vercel/remix/issues/124#issuecomment-2253590195) on the other issue: https://vercel-remix-fetch-353n1cyuk-uncurated-tests.vercel.app/login
